### PR TITLE
Describe action outputs in the readme

### PR DESCRIPTION
**Pull request by metiletan**

### CODE REVIEW

**Comment by metiletan** [comment]
@yxxhero I've updated the readme as you asked

**Comment by metiletan** [comment]
@yxxhero Could you please make a new release after merging this? I need this to switch my pipeline to upstream from my fork

**Review by yxxhero — APPROVED** [review]

**Comment by yxxhero** [comment]
@metiletan done

**Comment by metiletan** [comment]
@yxxhero Thank you very much!

**Pull request merged**
